version: "3"
services:
  node1:
    container_name: "node1"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  node2:
    container_name: "node2"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
  redis:
    image: redis
    ports:
      - "6379:6379"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node1
      - node2
